# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/dottie"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.11.2/dottie_Darwin_x86_64.tar.gz"
      sha256 "3ed28b7c760c8a5f22d459b7902103ac310495bd66e3814b5b6bdde625b8de1e"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jippi/dottie/releases/download/v0.11.2/dottie_Darwin_arm64.tar.gz"
      sha256 "d8dd25f76974eb206092615c05fe674cf1a5c4690833892e69ca531b193227ff"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.11.2/dottie_Linux_x86_64.tar.gz"
      sha256 "92854ac1d8c4a1dc725a85c02dd173e84b819e1a52a8bd8e977aeff41335148c"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.11.2/dottie_Linux_armv7.tar.gz"
      sha256 "05926c7d097a4083acc9ab45b716d1510aea8dcf46682c06c0dff1f7cdd2341c"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.11.2/dottie_Linux_arm64.tar.gz"
      sha256 "82d3211fe5059e554ce248b6242a3d7c69e9bfad8de2a7a8fd901e287d419632"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  test do
    system "#{bin}/dottie -v"
  end
end
