# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/dottie"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.0.10/dottie_Darwin_x86_64.tar.gz"
      sha256 "573332ad1c3a54598ea37d408144549761f907e822422982454c781aa2721754"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jippi/dottie/releases/download/v0.0.10/dottie_Darwin_arm64.tar.gz"
      sha256 "5847a7f7e673036104bf9a74a5bd6d63bac5fcaf18ef89f5d495fd4d22c3e82c"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.0.10/dottie_Linux_armv7.tar.gz"
      sha256 "7ab20fb70b1a31767991567a80c6a2d45f2393777edb4d177645255ca9b26439"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.0.10/dottie_Linux_x86_64.tar.gz"
      sha256 "857ed3280bab2e62f332f3a950f3fab2b39aef750fc5bc4aab9f3c816cf0111b"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.0.10/dottie_Linux_arm64.tar.gz"
      sha256 "70300b319aee2e19493f9a4e7f9bfd93841dda6c1dafd40f8e7ef36ec3a8f16e"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  test do
    system "#{bin}/dottie -v"
  end
end
