# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dottie < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/dottie"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.7.0/dottie_Darwin_x86_64.tar.gz"
      sha256 "56c8dca809d30c84d0e2c22543c6a1ec0caa029dd4bfd6f846ab74761720d8d7"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jippi/dottie/releases/download/v0.7.0/dottie_Darwin_arm64.tar.gz"
      sha256 "6c8a0da8e91c706ed819998b059034672c6e1900a351398267a704fab293bcd8"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.7.0/dottie_Linux_arm64.tar.gz"
      sha256 "fedff3246c2fd68cca794e13d8f3ab8ea28fcdeabace903a4b8408ddd0851c36"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/dottie/releases/download/v0.7.0/dottie_Linux_armv7.tar.gz"
      sha256 "cf713198bd4b7e057b694ada01eba2f8511c693851bc6c4b532a429134baf902"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jippi/dottie/releases/download/v0.7.0/dottie_Linux_x86_64.tar.gz"
      sha256 "c067315e87db4d3ced4e98c1e1b108c9e8050470d806ef75a323b36b8653a38d"

      def install
        bin.install "dottie"
        bash_completion.install "completions/dottie.bash" => "dottie"
        zsh_completion.install "completions/dottie.zsh" => "_dottie"
        fish_completion.install "completions/dottie.fish"
        man1.install "manpages/dottie.1.gz"
      end
    end
  end

  test do
    system "#{bin}/dottie -v"
  end
end
