# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScmEngine < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/scm-engine"
  version "0.16.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jippi/scm-engine/releases/download/v0.16.0/scm-engine_Darwin_x86_64.tar.gz"
      sha256 "9ec6a47a59c7994980b9b06ed500b3413aa4115af393c8b8c3a941a3494c577f"

      def install
        bin.install "scm-engine"
      end
    end
    on_arm do
      url "https://github.com/jippi/scm-engine/releases/download/v0.16.0/scm-engine_Darwin_arm64.tar.gz"
      sha256 "5574222a215550097deb2405af0ebd56350831532b76c1daac6282423d01e198"

      def install
        bin.install "scm-engine"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.16.0/scm-engine_Linux_x86_64.tar.gz"
        sha256 "eca84f65959eae5823b7d521d35e1be3df403a1a5b6f51c10ea59ad889578de4"

        def install
          bin.install "scm-engine"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.16.0/scm-engine_Linux_armv7.tar.gz"
        sha256 "9596e7a63351aebd7f482cb48e8917ca37f1a084ba944ed91c313447f7bcc4ed"

        def install
          bin.install "scm-engine"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.16.0/scm-engine_Linux_arm64.tar.gz"
        sha256 "6b18926161413164fabc0e42c57eaa1561fbb407f74f3bca1012c9dcb2520392"

        def install
          bin.install "scm-engine"
        end
      end
    end
  end

  test do
    system "#{bin}/scm-engine -v"
  end
end
