# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScmEngine < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/scm-engine"
  version "0.10.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jippi/scm-engine/releases/download/v0.10.9/scm-engine_Darwin_x86_64.tar.gz"
      sha256 "0a308b9d334bb253fadd908701fc21db000236f10e45e4d4a4571e7dd92a5b70"

      def install
        bin.install "scm-engine"
      end
    end
    on_arm do
      url "https://github.com/jippi/scm-engine/releases/download/v0.10.9/scm-engine_Darwin_arm64.tar.gz"
      sha256 "d25b96c7b09e6747bc00f29f13e0aba974b3548f5c33b05ef406ddc6c2b15ef2"

      def install
        bin.install "scm-engine"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.10.9/scm-engine_Linux_x86_64.tar.gz"
        sha256 "d0720b2e2554b68d2fa4d3b5bc2a3cd5761cf044f02ad9d242079ebb337c23be"

        def install
          bin.install "scm-engine"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.10.9/scm-engine_Linux_armv7.tar.gz"
        sha256 "647b06c3983c3fa2ab6b4edd0e5f890135bfc1b81b3e278cbeff65a82d4974d2"

        def install
          bin.install "scm-engine"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jippi/scm-engine/releases/download/v0.10.9/scm-engine_Linux_arm64.tar.gz"
        sha256 "62cce1035695c7abc087faf8431b1c82204ecaeff81c0c3c051234cff8e7cd0a"

        def install
          bin.install "scm-engine"
        end
      end
    end
  end

  test do
    system "#{bin}/scm-engine -v"
  end
end
