# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScmEngine < Formula
  desc "Makes working with .env files easy"
  homepage "https://github.com/jippi/scm-engine"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/scm-engine/releases/download/v0.0.4/scm-engine_Darwin_x86_64.tar.gz"
      sha256 "f34e9f68a7402c1dee29eea627643b3e696d4171b0ca329964180fbf0ce08fd1"

      def install
        bin.install "scm-engine"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jippi/scm-engine/releases/download/v0.0.4/scm-engine_Darwin_arm64.tar.gz"
      sha256 "4d003b5f4792f104faffe80e84635a92fa47a2397a5b73c2b5ace6e22b98e9ca"

      def install
        bin.install "scm-engine"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jippi/scm-engine/releases/download/v0.0.4/scm-engine_Linux_x86_64.tar.gz"
      sha256 "5d3413a0a7d8873aac92ffeea374f2ce82d3141ef780bed94d4cf0f3bdbd2af4"

      def install
        bin.install "scm-engine"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/scm-engine/releases/download/v0.0.4/scm-engine_Linux_armv7.tar.gz"
      sha256 "c71742308e252e03a3b5ee721a184374cb3c83d7c101f1f3ca2bc9e012862624"

      def install
        bin.install "scm-engine"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jippi/scm-engine/releases/download/v0.0.4/scm-engine_Linux_arm64.tar.gz"
      sha256 "794b49df91b759ff5adda41ff2503cf70de02eea4201d2001d68c3409a3b3d1d"

      def install
        bin.install "scm-engine"
      end
    end
  end

  test do
    system "#{bin}/scm-engine -v"
  end
end
